server:
  port: 8112

logging:
  #file:
  #  name: logfile.txt
  pattern:
  #console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([trace=%X{X-Trace-Id:-}, span=X{X-Span-Id:-}]){yellow} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%replace(%xException){'\n','\u2028'}%nopex%n"
  level:
    org:
      springframework:
        web: WARN
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE


spring:
  application:
    name: proposal-resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8190/realms/beea-shadhi

  datasource:
    url: jdbc:postgresql://localhost:5433/proposaldb
    username: proposaldb
    password: proposaldb
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
      show_sql: true
      format_sql: true
    generate-ddl: true
    properties:
      hibernate:
        default_schema: proposaldb
        #dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    enabled: false

# TODO:  matching service
matchingServiceUrl: http://localhost:8111/api/profiles
